version: '3'

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached
      # Docker
      - ~/.docker:/root/.docker:z
      # SSH directory for Linux, OSX and WSL
      # On Linux and OSX, a symlink /mnt/ssh <-> ~/.ssh is
      # created in the container. On Windows, files are copied
      # from /mnt/ssh to ~/.ssh to fix permissions.
      - ~/.ssh:/mnt/ssh
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig:z
      # Kubernetes
      - ~/.kube:/root/.kube:z
    # networks:
    #   - llm-benchmark-network
    environment:
      - TZ=
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined

    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]
    command: sleep infinity

networks:
  llm-benchmark-network:
    external: true
